### ISSUE TITLE
Understanding configuration options chosen

### ISSUE THREAD

**Issue by th31nitiate** [Bonn93/atlassian-kubernetes#1]
I am currently working on something similar. I forked the repo however I have not made any deployments. I am not sure if it will be possible with the current set. 

I am interested to know how you have this working with NFS. In the documentation, it mentions that it is not possible to run this on an NFS type system unless you have a data center version of the Atlassian suite enabled. 

I am interested to know how you managed to solve this storage issue. Our current solution is to use the EBS PV claim with one replica set.

**Comment by th31nitiate** [comment]
How did you manage to bypass the licensing issues? One of the main problems I see is around the licensing model and the server ID's. This pretty much defies the logic of kubernetes as an orchestrator since it will require a new license each and every time.

**Comment by Bonn93** [comment]
For the PVs, you'll need a system that supports ReadWriteMany. NFS and Gluster come to mind. It's also correct that NFS is needed for the "DC" version of Bitbucket, but you can run the data dir off NFS without that licence. 

As long as each pod has access to that PV as ReadWriteMany, they'll configure themselves with the bitbucket.properties file located there.

I've not by-passed licencing, however on the first deployment, you will need to complete this step in the web UI, this is then stored in the postgres database somewhere. If you really needed to automate this, I'd suggest something like Selenium that can access the UI elements to complete this stage. 

Does this answer your questions?

**Comment by Bonn93** [comment]
I'll close this out, let me know if you have any further questions
